// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLiGhiDanhAPI.Repository;

#nullable disable

namespace QuanLiGhiDanhAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240122140449_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLiGhiDanhAPI.Models.DangKy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("HocVienId")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianDangKy")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TinhTrangThanhToan")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HocVienId");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("DangKy");
                });

            modelBuilder.Entity("QuanLiGhiDanhAPI.Models.GiaoVien", b =>
                {
                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHopTac")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HoTen");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("GiaoVien");
                });

            modelBuilder.Entity("QuanLiGhiDanhAPI.Models.HocVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDTPhuHuynh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HocVien");
                });

            modelBuilder.Entity("QuanLiGhiDanhAPI.Models.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("QuanLiGhiDanhAPI.Models.LopHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GiaoVienChuNhiemHoTen")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GioHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<string>("NgayHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienChuNhiemHoTen");

                    b.HasIndex("MonHocId");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("QuanLiGhiDanhAPI.Models.MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GiaoVienHoTen")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NhomMonHocId")
                        .HasColumnType("int");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienHoTen");

                    b.HasIndex("NhomMonHocId");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("QuanLiGhiDanhAPI.Models.NhomMonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TênNhóm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NhomMonHoc");
                });

            modelBuilder.Entity("QuanLiGhiDanhAPI.Models.DangKy", b =>
                {
                    b.HasOne("QuanLiGhiDanhAPI.Models.HocVien", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLiGhiDanhAPI.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DanhSachDangKy")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("QuanLiGhiDanhAPI.Models.GiaoVien", b =>
                {
                    b.HasOne("QuanLiGhiDanhAPI.Models.KhoaHoc", null)
                        .WithMany("DanhSachGiaoVien")
                        .HasForeignKey("KhoaHocId");
                });

            modelBuilder.Entity("QuanLiGhiDanhAPI.Models.LopHoc", b =>
                {
                    b.HasOne("QuanLiGhiDanhAPI.Models.GiaoVien", "GiaoVienChuNhiem")
                        .WithMany()
                        .HasForeignKey("GiaoVienChuNhiemHoTen");

                    b.HasOne("QuanLiGhiDanhAPI.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVienChuNhiem");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("QuanLiGhiDanhAPI.Models.MonHoc", b =>
                {
                    b.HasOne("QuanLiGhiDanhAPI.Models.GiaoVien", null)
                        .WithMany("MonGiangDay")
                        .HasForeignKey("GiaoVienHoTen");

                    b.HasOne("QuanLiGhiDanhAPI.Models.NhomMonHoc", null)
                        .WithMany("DanhSachMonHoc")
                        .HasForeignKey("NhomMonHocId");
                });

            modelBuilder.Entity("QuanLiGhiDanhAPI.Models.GiaoVien", b =>
                {
                    b.Navigation("MonGiangDay");
                });

            modelBuilder.Entity("QuanLiGhiDanhAPI.Models.KhoaHoc", b =>
                {
                    b.Navigation("DanhSachDangKy");

                    b.Navigation("DanhSachGiaoVien");
                });

            modelBuilder.Entity("QuanLiGhiDanhAPI.Models.NhomMonHoc", b =>
                {
                    b.Navigation("DanhSachMonHoc");
                });
#pragma warning restore 612, 618
        }
    }
}
